// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACV-ZUUT1elcWVsKxbr9Lf0lRrcnV54qo',
    appId: '1:652501621128:web:6f2a1dd3895e73461b423d',
    messagingSenderId: '652501621128',
    projectId: 'productreivew',
    authDomain: 'productreivew.firebaseapp.com',
    storageBucket: 'productreivew.firebasestorage.app',
    measurementId: 'G-KRF25CTYLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHdEr7Csy4JiAw5tIq5C-HJTfPDScBqkQ',
    appId: '1:652501621128:android:ebdf01d391ad67a41b423d',
    messagingSenderId: '652501621128',
    projectId: 'productreivew',
    storageBucket: 'productreivew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIa-P7JXxfGf1qNhugKpRxF4YuRCSwG8I',
    appId: '1:652501621128:ios:71664c34ef8a224e1b423d',
    messagingSenderId: '652501621128',
    projectId: 'productreivew',
    storageBucket: 'productreivew.firebasestorage.app',
    iosBundleId: 'com.example.productReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIa-P7JXxfGf1qNhugKpRxF4YuRCSwG8I',
    appId: '1:652501621128:ios:71664c34ef8a224e1b423d',
    messagingSenderId: '652501621128',
    projectId: 'productreivew',
    storageBucket: 'productreivew.firebasestorage.app',
    iosBundleId: 'com.example.productReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACV-ZUUT1elcWVsKxbr9Lf0lRrcnV54qo',
    appId: '1:652501621128:web:6f2a1dd3895e73461b423d',
    messagingSenderId: '652501621128',
    projectId: 'productreivew',
    authDomain: 'productreivew.firebaseapp.com',
    storageBucket: 'productreivew.firebasestorage.app',
    measurementId: 'G-KRF25CTYLN',
  );

}